// ─────────────────────────────────────────────────────────────
// apps/tools — Notepad, Paint, Media Player, MS-DOS Prompt.
// ─────────────────────────────────────────────────────────────
import { C, FONT, bevelOut, bevelIn, etchIn, fill, text, button, drawIcon, scrollBar, arrow } from '../ui.js';

// ── Notepad ──────────────────────────────────────────────────
const FILES = {
  readme: {
    name: 'README.TXT',
    body: `PORTFOLIO.98
============

Thank you for booting me up.

WHAT THIS IS
------------
You are looking at a bedroom that does not exist, rendered in
real time in your web browser, containing a computer that does
not exist, running an operating system that does not exist,
displaying a text file that arguably does.

None of it was downloaded. There are no 3D model files in this
project and no image files either. Every surface, every fold in
the duvet, every wrinkle on the dog, and every pixel of this
window was generated by code when the page loaded.

HOW TO GET AROUND
-----------------
  WASD ............ walk
  Mouse ........... look
  Shift ........... run
  E ............... sit down at the computer / stand up
  Esc ............. release the mouse

INSIDE THE COMPUTER
-------------------
  * Double-click things. Most of them work.
  * The web browser needs a dial-up connection first.
    Open Dial-Up Networking and click Connect.
    It takes about ten seconds, and yes, it makes the noise.
  * Minesweeper is a real, complete Minesweeper.
  * Snake is real too.
  * Paint saves nothing, like the original.
  * Leave the machine alone for a while and it will
    show you a screensaver.

THINGS TO TRY
-------------
  * Press Ctrl+Alt+Delete.
  * Type HELP in the MS-DOS Prompt.
  * Look under the desk.
  * Say hello to the dog.

-- Kyle
`,
  },
  resume: {
    name: 'RESUME.TXT',
    body: `KYLE BYARS
Software Developer

CONTACT
  E-Mail .... kylebyars@outlook.com
  GitHub .... github.com/ByarsKyle

WHAT I DO
  I build web applications and internal tools - the kind of
  software that quietly saves somebody an hour every day.
  I like small, fast, obvious interfaces and short feedback
  loops.

STACK
  JavaScript / TypeScript, Node, React
  Python where it fits
  Postgres, Supabase
  WebGL / Three.js
  Whatever the problem actually needs

SELECTED WORK
  CallGuard ....... call handling and screening tooling
  PoolSurf ........ service business platform: scheduling,
                    routes, customers
  Personal OS ..... personal finance and life dashboard
  HHN Alert ....... ticket-drop monitor with a loud opinion
  Portfolio.98 .... this. ~6,000 lines of procedural WebGL.

NOTE
  This file is a placeholder living inside a fake operating
  system. Replace it with the real thing in
  src/os/apps/tools.js before anyone important reads it.
`,
  },
  todo: {
    name: 'TODO.TXT',
    body: `TODO
====

[x] build the room
[x] make the bed look like a bed and not a box
[x] cloth sim for the duvet
[x] CRT shader - scanlines, curvature, that glow
[x] boot sequence
[x] dial-up noise (accurate to a fault)
[x] the dog
[ ] the dog should follow you around
[ ] make the window openable
[ ] add a cat for balance
[ ] stop redesigning this and ship it
[ ] sleep

-- notes --
The pug is 16,000 fur shells. It was 40,000 but the laptop
started making a noise.

If you are reading this in the browser: the file you are
looking at is a string in a JavaScript file being drawn to
a 2D canvas which is a texture on a curved mesh inside a
3D scene. Hello from in here.
`,
  },
  source: {
    name: 'SOURCE.HTM',
    body: `<HTML>
<HEAD>
<TITLE>Kyle's Corner of the Web</TITLE>
<META NAME="GENERATOR" CONTENT="Microsoft FrontPage Express 2.0">
</HEAD>
<BODY BGCOLOR="#C8D8F0" TEXT="#000000" LINK="#0000EE" VLINK="#551A8B">

<CENTER>
<IMG SRC="banner.gif" WIDTH=400 HEIGHT=56 ALT="Kyle's Corner">
<MARQUEE BGCOLOR="#000080"><FONT COLOR="#FFFF00">
*** WELCOME TO MY HOMEPAGE *** BEST VIEWED IN 800x600 ***
</FONT></MARQUEE>
</CENTER>

<H1>Hi, I build things.</H1>
<P>You've reached the personal homepage of Kyle Byars...</P>

<HR>
<!-- TODO: fix the guestbook CGI, it has been down since June -->
<!-- TODO: the counter is a lie -->

<CENTER>
<IMG SRC="construction.gif" ALT="Under Construction">
</CENTER>

</BODY>
</HTML>
`,
  },
  empty: { name: 'Untitled', body: '' },
};

export const notepad = {
  title: 'Notepad',
  icon: 'notepad',
  w: 400, h: 300,

  create(arg, api) {
    const file = FILES[arg] ?? FILES.empty;
    const st = {
      lines: file.body.split('\n'),
      name: file.name,
      cursor: { line: 0, col: 0 },
      scroll: 0,
      blink: 0,
      wrap: false,
      dirty: false,
    };

    const LH = 13;

    const app = {
      title: `${file.name} - Notepad`,
      icon: 'notepad',
      w: 420, h: 300,
      minW: 220, minH: 140,
      menus: [
        { label: 'File', items: [
          { label: 'New', id: 'new' }, { label: 'Open...', id: 'open' },
          { label: 'Save', id: 'save', accel: 'Ctrl+S' }, { label: 'Save As...', id: 'saveas' },
          '-', { label: 'Print', id: 'print' }, '-', { label: 'Exit', id: 'exit' },
        ] },
        { label: 'Edit', items: [
          { label: 'Undo', disabled: true, accel: 'Ctrl+Z' }, '-',
          { label: 'Cut', accel: 'Ctrl+X', disabled: true },
          { label: 'Copy', accel: 'Ctrl+C', disabled: true },
          { label: 'Paste', accel: 'Ctrl+V', disabled: true },
          '-', { label: 'Select All', id: 'selectall', accel: 'Ctrl+A' },
          { label: 'Time/Date', id: 'timedate', accel: 'F5' },
        ] },
        { label: 'Search', items: [{ label: 'Find...', id: 'find', accel: 'Ctrl+F' }, { label: 'Find Next', disabled: true }] },
        { label: 'Help', items: [{ label: 'Help Topics', id: 'help' }, '-', { label: 'About Notepad', id: 'about' }] },
      ],

      command(id, win, papi) {
        if (id === 'exit' || id === 'Exit') papi.close(win);
        else if (id === 'new' || id === 'New') { st.lines = ['']; st.name = 'Untitled'; win.title = 'Untitled - Notepad'; st.cursor = { line: 0, col: 0 }; }
        else if (id === 'save' || id === 'Save' || id === 'saveas') {
          papi.messageBox('Notepad', 'Cannot create the file.\n\nThe disk is write-protected,\nor imaginary.', { icon: 'error', w: 290 });
        } else if (id === 'open' || id === 'Open...') {
          papi.messageBox('Open', 'This dialog is not implemented.\n\nTry the Documents folder in the\nStart menu instead.', { icon: 'info', w: 300 });
        } else if (id === 'print' || id === 'Print') {
          papi.messageBox('Notepad', 'There is no printer attached.\n\nThere was never a printer attached.', { icon: 'warn', w: 300 });
        } else if (id === 'timedate' || id === 'Time/Date') {
          const d = new Date();
          const s = `${d.toLocaleTimeString()} ${d.toLocaleDateString()}`;
          insert(s);
        } else if (id === 'about' || id === 'About Notepad') {
          papi.messageBox('About Notepad', 'Notepad\nMicrosoft (R) Windows (R) 98\n\nIt opens text. That is the whole product.', { icon: 'notepad', w: 300 });
        } else if (id === 'help' || id === 'Help Topics') {
          papi.messageBox('Windows Help', 'Help is not available for this topic.\n\nIt was 1998. Nobody read it anyway.', { icon: 'help', w: 300 });
        }
      },

      key(e, win, papi) {
        const c = st.cursor;
        const line = st.lines[c.line] ?? '';
        st.blink = 0;
        if (e.ctrlKey) {
          if (e.key === 's') { app.command('save', win, papi); }
          return;
        }
        switch (e.key) {
          case 'ArrowLeft':
            if (c.col > 0) c.col--;
            else if (c.line > 0) { c.line--; c.col = st.lines[c.line].length; }
            break;
          case 'ArrowRight':
            if (c.col < line.length) c.col++;
            else if (c.line < st.lines.length - 1) { c.line++; c.col = 0; }
            break;
          case 'ArrowUp':
            if (c.line > 0) { c.line--; c.col = Math.min(c.col, st.lines[c.line].length); }
            break;
          case 'ArrowDown':
            if (c.line < st.lines.length - 1) { c.line++; c.col = Math.min(c.col, st.lines[c.line].length); }
            break;
          case 'Home': c.col = 0; break;
          case 'End': c.col = line.length; break;
          case 'PageUp': c.line = Math.max(0, c.line - 12); c.col = Math.min(c.col, st.lines[c.line].length); break;
          case 'PageDown': c.line = Math.min(st.lines.length - 1, c.line + 12); c.col = Math.min(c.col, st.lines[c.line].length); break;
          case 'Backspace':
            if (c.col > 0) {
              st.lines[c.line] = line.slice(0, c.col - 1) + line.slice(c.col);
              c.col--;
            } else if (c.line > 0) {
              const prev = st.lines[c.line - 1];
              st.lines[c.line - 1] = prev + line;
              st.lines.splice(c.line, 1);
              c.line--; c.col = prev.length;
            }
            st.dirty = true;
            break;
          case 'Delete':
            if (c.col < line.length) st.lines[c.line] = line.slice(0, c.col) + line.slice(c.col + 1);
            else if (c.line < st.lines.length - 1) {
              st.lines[c.line] = line + st.lines[c.line + 1];
              st.lines.splice(c.line + 1, 1);
            }
            st.dirty = true;
            break;
          case 'Enter':
            st.lines.splice(c.line + 1, 0, line.slice(c.col));
            st.lines[c.line] = line.slice(0, c.col);
            c.line++; c.col = 0;
            st.dirty = true;
            break;
          case 'Tab': insert('    '); break;
          default:
            if (e.key.length === 1) insert(e.key);
        }
        // keep the caret on screen
        const visible = Math.floor((win.h - 60) / LH);
        if (c.line < st.scroll) st.scroll = c.line;
        if (c.line > st.scroll + visible - 1) st.scroll = c.line - visible + 1;
      },

      update(dt) { st.blink += dt; },

      draw(ctx, r, win) {
        fill(ctx, r.x, r.y, r.w, r.h, C.face);
        const SB = 15;
        const view = { x: r.x + 2, y: r.y + 2, w: r.w - 4 - SB, h: r.h - 4 - SB };
        fill(ctx, view.x, view.y, view.w + SB, view.h + SB, C.white);
        bevelIn(ctx, r.x, r.y, r.w, r.h);

        ctx.save();
        ctx.beginPath(); ctx.rect(view.x, view.y, view.w, view.h); ctx.clip();
        ctx.font = FONT.mono;
        const visible = Math.ceil(view.h / LH);
        for (let i = 0; i < visible; i++) {
          const li = st.scroll + i;
          if (li >= st.lines.length) break;
          text(ctx, st.lines[li], view.x + 3, view.y + 2 + i * LH, { font: FONT.mono, color: '#000' });
        }
        // caret
        if (Math.floor(st.blink * 2) % 2 === 0) {
          const cl = st.cursor.line - st.scroll;
          if (cl >= 0 && cl < visible) {
            const pre = (st.lines[st.cursor.line] ?? '').slice(0, st.cursor.col);
            const cx = view.x + 3 + ctx.measureText(pre).width;
            fill(ctx, cx, view.y + 2 + cl * LH, 1, LH - 1, '#000');
          }
        }
        ctx.restore();

        st.maxScroll = Math.max(0, st.lines.length - Math.floor(view.h / LH));
        st.view = view;
        scrollBar(ctx, r.x + r.w - SB - 2, r.y + 2, SB, r.h - 4 - SB, st.scroll, view.h / LH, st.lines.length, true);
        scrollBar(ctx, r.x + 2, r.y + r.h - SB - 2, r.w - 4 - SB, SB, 0, 1, 1, false);
      },

      mouse(type, x, y, btn, win, papi) {
        if (type !== 'down' && type !== 'dblclick') return;
        const view = st.view;
        if (!view) return;
        const b = win.maximized ? { x: 0, y: 0 } : { x: win.x, y: win.y };
        const ax = x + b.x + 3, ay = y + b.y + 40;
        // scroll wheel substitutes: clicking the bar
        if (ax > view.x + view.w) {
          if (ay < view.y + 15) st.scroll = Math.max(0, st.scroll - 3);
          else if (ay > view.y + view.h - 15) st.scroll = Math.min(st.maxScroll, st.scroll + 3);
          else st.scroll = Math.round(((ay - view.y - 15) / Math.max(1, view.h - 30)) * st.maxScroll);
          return;
        }
        if (ax >= view.x && ax <= view.x + view.w && ay >= view.y && ay <= view.y + view.h) {
          const li = Math.min(st.lines.length - 1, st.scroll + Math.floor((ay - view.y - 2) / LH));
          st.cursor.line = Math.max(0, li);
          // find the nearest column
          const lineStr = st.lines[st.cursor.line] ?? '';
          let best = 0, bestD = 1e9;
          for (let i = 0; i <= lineStr.length; i++) {
            const wpx = view.x + 3 + measure(lineStr.slice(0, i));
            const d = Math.abs(wpx - ax);
            if (d < bestD) { bestD = d; best = i; }
          }
          st.cursor.col = best;
          st.blink = 0;
        }
      },
    };

    let _ctx = null;
    function measure(s) {
      if (!_ctx) {
        const c = document.createElement('canvas');
        _ctx = c.getContext('2d');
      }
      _ctx.font = FONT.mono;
      return _ctx.measureText(s).width;
    }

    function insert(s) {
      const c = st.cursor;
      const line = st.lines[c.line] ?? '';
      st.lines[c.line] = line.slice(0, c.col) + s + line.slice(c.col);
      c.col += s.length;
      st.dirty = true;
    }

    return app;
  },
};

// ── Paint ────────────────────────────────────────────────────
export const paint = {
  title: 'untitled - Paint',
  icon: 'paint',
  w: 400, h: 300,
  single: true,

  create(arg, api) {
    const buf = document.createElement('canvas');
    buf.width = 320; buf.height = 200;
    const bctx = buf.getContext('2d');
    bctx.fillStyle = '#ffffff';
    bctx.fillRect(0, 0, buf.width, buf.height);

    const PALETTE = [
      '#000000', '#808080', '#800000', '#808000', '#008000', '#008080', '#000080', '#800080',
      '#808040', '#004040', '#0080ff', '#004080', '#8000ff', '#804000',
      '#ffffff', '#c0c0c0', '#ff0000', '#ffff00', '#00ff00', '#00ffff', '#0000ff', '#ff00ff',
      '#ffff80', '#00ff80', '#80ffff', '#8080ff', '#ff0080', '#ff8040',
    ];
    const TOOLS = ['pencil', 'brush', 'eraser', 'fill', 'line', 'rect', 'ellipse', 'spray'];

    const st = {
      tool: 'brush', color: '#000000', color2: '#ffffff',
      drawing: false, last: null, start: null, size: 2,
    };

    function toBuf(ax, ay, canvasRect) {
      return {
        x: Math.floor((ax - canvasRect.x) * (buf.width / canvasRect.w)),
        y: Math.floor((ay - canvasRect.y) * (buf.height / canvasRect.h)),
      };
    }

    function stroke(a, b) {
      bctx.strokeStyle = st.tool === 'eraser' ? '#ffffff' : st.color;
      bctx.lineWidth = st.tool === 'eraser' ? 12 : (st.tool === 'brush' ? 3 : 1.4);
      bctx.lineCap = 'round'; bctx.lineJoin = 'round';
      bctx.beginPath();
      bctx.moveTo(a.x, a.y); bctx.lineTo(b.x, b.y);
      bctx.stroke();
    }

    function floodFill(px, py, hex) {
      const img = bctx.getImageData(0, 0, buf.width, buf.height);
      const d = img.data;
      const idx = (x, y) => (y * buf.width + x) * 4;
      const target = [d[idx(px, py)], d[idx(px, py) + 1], d[idx(px, py) + 2]];
      const rgb = [parseInt(hex.slice(1, 3), 16), parseInt(hex.slice(3, 5), 16), parseInt(hex.slice(5, 7), 16)];
      if (target[0] === rgb[0] && target[1] === rgb[1] && target[2] === rgb[2]) return;
      const stack = [[px, py]];
      const seen = new Uint8Array(buf.width * buf.height);
      while (stack.length) {
        const [x, y] = stack.pop();
        if (x < 0 || y < 0 || x >= buf.width || y >= buf.height) continue;
        const k = y * buf.width + x;
        if (seen[k]) continue;
        const i = k * 4;
        if (Math.abs(d[i] - target[0]) > 12 || Math.abs(d[i + 1] - target[1]) > 12 || Math.abs(d[i + 2] - target[2]) > 12) continue;
        seen[k] = 1;
        d[i] = rgb[0]; d[i + 1] = rgb[1]; d[i + 2] = rgb[2];
        stack.push([x + 1, y], [x - 1, y], [x, y + 1], [x, y - 1]);
      }
      bctx.putImageData(img, 0, 0);
    }

    const app = {
      title: 'untitled - Paint', icon: 'paint',
      w: 400, h: 300, minW: 300, minH: 220,
      menus: [
        { label: 'File', items: [{ label: 'New', id: 'new' }, { label: 'Save', id: 'save' }, '-', { label: 'Exit', id: 'exit' }] },
        { label: 'Edit', items: [{ label: 'Undo', disabled: true }, { label: 'Clear Image', id: 'new' }] },
        { label: 'Image', items: [{ label: 'Flip/Rotate', id: 'flip' }, { label: 'Invert Colors', id: 'invert' }] },
        { label: 'Help', items: [{ label: 'About Paint', id: 'about' }] },
      ],
      command(id, win, papi) {
        if (id === 'exit' || id === 'Exit') papi.close(win);
        else if (id === 'new' || id === 'New' || id === 'Clear Image') {
          bctx.fillStyle = '#ffffff'; bctx.fillRect(0, 0, buf.width, buf.height);
        } else if (id === 'save' || id === 'Save') {
          papi.messageBox('Paint', 'Cannot save to A:\\\n\nInsert a disk and try again.', { icon: 'error', w: 280 });
        } else if (id === 'invert' || id === 'Invert Colors') {
          const img = bctx.getImageData(0, 0, buf.width, buf.height);
          const d = img.data;
          for (let i = 0; i < d.length; i += 4) { d[i] = 255 - d[i]; d[i + 1] = 255 - d[i + 1]; d[i + 2] = 255 - d[i + 2]; }
          bctx.putImageData(img, 0, 0);
        } else if (id === 'flip' || id === 'Flip/Rotate') {
          const tmp = document.createElement('canvas');
          tmp.width = buf.width; tmp.height = buf.height;
          tmp.getContext('2d').drawImage(buf, 0, 0);
          bctx.save(); bctx.scale(-1, 1); bctx.drawImage(tmp, -buf.width, 0); bctx.restore();
        } else if (id === 'about' || id === 'About Paint') {
          papi.messageBox('About Paint', 'Microsoft Paint\n\nStill the fastest way to crop a\nscreenshot, twenty-five years later.', { icon: 'paint', w: 300 });
        }
      },
      draw(ctx, r, win) {
        fill(ctx, r.x, r.y, r.w, r.h, C.face);

        // tool box
        const tbW = 34;
        st.toolRects = [];
        TOOLS.forEach((t, i) => {
          const bx = r.x + 2 + (i % 2) * 16;
          const by = r.y + 2 + Math.floor(i / 2) * 16;
          button(ctx, bx, by, 16, 16, null, { pressed: st.tool === t });
          drawTool(ctx, t, bx + 8, by + 8, st.tool === t);
          st.toolRects.push({ x: bx, y: by, w: 16, h: 16, tool: t });
        });

        // canvas area
        const cw = r.w - tbW - 8, ch = r.h - 46;
        const cx = r.x + tbW + 4, cy = r.y + 2;
        fill(ctx, cx, cy, cw, ch, '#808080');
        const scale = Math.min(cw / buf.width, ch / buf.height, 1.4);
        const dw = Math.floor(buf.width * scale), dh = Math.floor(buf.height * scale);
        const dx = cx + 4, dy = cy + 4;
        bevelIn(ctx, dx - 2, dy - 2, dw + 4, dh + 4);
        ctx.imageSmoothingEnabled = false;
        ctx.drawImage(buf, dx, dy, dw, dh);
        st.canvasRect = { x: dx, y: dy, w: dw, h: dh };

        // preview of the in-progress shape
        if (st.drawing && st.start && st.preview && ['line', 'rect', 'ellipse'].includes(st.tool)) {
          ctx.save();
          ctx.strokeStyle = st.color; ctx.lineWidth = 1;
          const sx = dx + st.start.x * scale, sy = dy + st.start.y * scale;
          const ex = dx + st.preview.x * scale, ey = dy + st.preview.y * scale;
          ctx.beginPath();
          if (st.tool === 'line') { ctx.moveTo(sx, sy); ctx.lineTo(ex, ey); }
          else if (st.tool === 'rect') ctx.rect(sx, sy, ex - sx, ey - sy);
          else ctx.ellipse((sx + ex) / 2, (sy + ey) / 2, Math.abs(ex - sx) / 2, Math.abs(ey - sy) / 2, 0, 0, Math.PI * 2);
          ctx.stroke();
          ctx.restore();
        }

        // palette
        const py = r.y + r.h - 34;
        fill(ctx, r.x + 2, py, r.w - 4, 32, C.face);
        // current colours
        bevelIn(ctx, r.x + 4, py + 4, 26, 24);
        fill(ctx, r.x + 16, py + 14, 12, 12, st.color2);
        ctx.strokeStyle = '#000'; ctx.strokeRect(r.x + 16.5, py + 14.5, 11, 11);
        fill(ctx, r.x + 8, py + 8, 12, 12, st.color);
        ctx.strokeRect(r.x + 8.5, py + 8.5, 11, 11);

        st.palRects = [];
        PALETTE.forEach((col, i) => {
          const px = r.x + 36 + (i % 14) * 15;
          const pyy = py + 4 + Math.floor(i / 14) * 13;
          fill(ctx, px, pyy, 13, 11, col);
          bevelIn(ctx, px, pyy, 13, 11, 1);
          st.palRects.push({ x: px, y: pyy, w: 13, h: 11, color: col });
        });
      },
      mouse(type, x, y, btn, win, papi) {
        const b = win.maximized ? { x: 0, y: 0 } : { x: win.x, y: win.y };
        const ax = x + b.x + 3, ay = y + b.y + 40;

        if (type === 'down') {
          for (const t of st.toolRects ?? []) {
            if (ax >= t.x && ax <= t.x + t.w && ay >= t.y && ay <= t.y + t.h) {
              st.tool = t.tool; papi.sound('click'); return;
            }
          }
          for (const p of st.palRects ?? []) {
            if (ax >= p.x && ax <= p.x + p.w && ay >= p.y && ay <= p.y + p.h) {
              if (btn === 2) st.color2 = p.color; else st.color = p.color;
              papi.sound('click'); return;
            }
          }
        }

        const cr = st.canvasRect;
        if (!cr) return;
        const inside = ax >= cr.x && ax <= cr.x + cr.w && ay >= cr.y && ay <= cr.y + cr.h;
        const p = toBuf(ax, ay, cr);

        if (type === 'down' && inside) {
          st.drawing = true;
          st.start = p; st.last = p; st.preview = p;
          if (st.tool === 'fill') { floodFill(p.x, p.y, btn === 2 ? st.color2 : st.color); st.drawing = false; }
          else if (st.tool === 'pencil' || st.tool === 'brush' || st.tool === 'eraser') stroke(p, p);
          else if (st.tool === 'spray') spray(p);
        } else if (type === 'move' && st.drawing) {
          st.preview = p;
          if (st.tool === 'pencil' || st.tool === 'brush' || st.tool === 'eraser') { stroke(st.last, p); st.last = p; }
          else if (st.tool === 'spray') spray(p);
        } else if (type === 'up' && st.drawing) {
          if (['line', 'rect', 'ellipse'].includes(st.tool) && st.start) {
            bctx.strokeStyle = st.color; bctx.lineWidth = 1.4;
            bctx.beginPath();
            if (st.tool === 'line') { bctx.moveTo(st.start.x, st.start.y); bctx.lineTo(p.x, p.y); }
            else if (st.tool === 'rect') bctx.rect(st.start.x, st.start.y, p.x - st.start.x, p.y - st.start.y);
            else bctx.ellipse((st.start.x + p.x) / 2, (st.start.y + p.y) / 2,
              Math.abs(p.x - st.start.x) / 2, Math.abs(p.y - st.start.y) / 2, 0, 0, Math.PI * 2);
            bctx.stroke();
          }
          st.drawing = false; st.start = null;
        }
      },
    };

    function spray(p) {
      bctx.fillStyle = st.color;
      for (let i = 0; i < 12; i++) {
        const a = Math.random() * Math.PI * 2, rr = Math.random() * 7;
        bctx.fillRect(p.x + Math.cos(a) * rr, p.y + Math.sin(a) * rr, 1, 1);
      }
    }

    function drawTool(ctx, t, cx, cy, on) {
      const o = on ? 1 : 0;
      ctx.save();
      ctx.translate(cx + o, cy + o);
      ctx.strokeStyle = '#000'; ctx.fillStyle = '#000'; ctx.lineWidth = 1;
      if (t === 'pencil') { ctx.beginPath(); ctx.moveTo(-4, 4); ctx.lineTo(3, -3); ctx.stroke(); ctx.fillRect(-5, 3, 2, 2); }
      else if (t === 'brush') { ctx.beginPath(); ctx.moveTo(-4, 4); ctx.lineTo(2, -2); ctx.lineWidth = 2.4; ctx.stroke(); ctx.beginPath(); ctx.arc(3, -3, 2, 0, Math.PI * 2); ctx.fill(); }
      else if (t === 'eraser') { ctx.fillStyle = '#fff'; ctx.fillRect(-4, -2, 8, 6); ctx.strokeRect(-4.5, -2.5, 9, 7); }
      else if (t === 'fill') { ctx.beginPath(); ctx.moveTo(-4, 0); ctx.lineTo(0, -4); ctx.lineTo(4, 0); ctx.lineTo(0, 4); ctx.closePath(); ctx.stroke(); ctx.fillRect(2, 2, 3, 4); }
      else if (t === 'line') { ctx.beginPath(); ctx.moveTo(-4, 4); ctx.lineTo(4, -4); ctx.stroke(); }
      else if (t === 'rect') ctx.strokeRect(-4.5, -3.5, 9, 7);
      else if (t === 'ellipse') { ctx.beginPath(); ctx.ellipse(0, 0, 4.5, 3.5, 0, 0, Math.PI * 2); ctx.stroke(); }
      else if (t === 'spray') { for (let i = 0; i < 9; i++) ctx.fillRect(-4 + (i * 7 % 9), -4 + (i * 5 % 9), 1, 1); }
      ctx.restore();
    }

    return app;
  },
};

// ── Media Player ─────────────────────────────────────────────
export const media = {
  title: 'Media Player',
  icon: 'media',
  w: 268, h: 174,
  single: true,
  resizable: false,

  create(arg, api) {
    const TRACKS = [
      { name: 'CANYON.MID', len: 92 },
      { name: 'PASSPORT.MID', len: 64 },
      { name: 'CLOUDS.MID', len: 78 },
    ];
    const st = { track: 0, playing: false, pos: 0, bars: new Array(28).fill(0), t: 0 };

    const app = {
      title: 'Media Player', icon: 'media', w: 268, h: 178, resizable: false,
      menus: [
        { label: 'File', items: [{ label: 'Open...', id: 'open' }, '-', { label: 'Exit', id: 'exit' }] },
        { label: 'Device', items: TRACKS.map((t, i) => ({ label: t.name, id: `track:${i}` })) },
        { label: 'Help', items: [{ label: 'About Media Player', id: 'about' }] },
      ],
      command(id, win, papi) {
        if (id === 'exit' || id === 'Exit') papi.close(win);
        else if (id?.startsWith('track:')) { st.track = +id.split(':')[1]; st.pos = 0; }
        else if (id === 'open' || id === 'Open...') papi.messageBox('Media Player', 'No media devices found.\n\nCheck that your sound card is\ninstalled and that the IRQ is not 5.', { icon: 'warn', w: 300 });
        else if (id === 'about') papi.messageBox('About', 'Microsoft Media Player\nVersion 5.1\n\nPlays three MIDI files. Beautifully.', { icon: 'media', w: 280 });
        else {
          const i = TRACKS.findIndex((t) => t.name === id);
          if (i >= 0) { st.track = i; st.pos = 0; }
        }
      },
      update(dt, win, papi) {
        st.t += dt;
        if (st.playing) {
          st.pos += dt;
          if (st.pos >= TRACKS[st.track].len) { st.pos = 0; st.track = (st.track + 1) % TRACKS.length; }
        }
        for (let i = 0; i < st.bars.length; i++) {
          const target = st.playing
            ? Math.abs(Math.sin(st.t * (1.6 + i * 0.19) + i)) * (0.35 + 0.65 * Math.abs(Math.sin(st.t * 0.8 + i * 0.4)))
            : 0;
          st.bars[i] += (target - st.bars[i]) * Math.min(1, dt * (target > st.bars[i] ? 16 : 6));
        }
      },
      draw(ctx, r, win, papi) {
        fill(ctx, r.x, r.y, r.w, r.h, C.face);
        // visualiser
        const vx = r.x + 6, vy = r.y + 6, vw = r.w - 12, vh = 74;
        bevelIn(ctx, vx, vy, vw, vh);
        fill(ctx, vx + 2, vy + 2, vw - 4, vh - 4, '#08121c');
        const bw = (vw - 10) / st.bars.length;
        st.bars.forEach((b, i) => {
          const h = Math.max(1, b * (vh - 12));
          const bx = vx + 4 + i * bw;
          for (let yy = 0; yy < h; yy += 3) {
            const frac = yy / (vh - 12);
            ctx.fillStyle = frac > 0.72 ? '#ff4040' : frac > 0.45 ? '#ffd040' : '#40e070';
            ctx.fillRect(bx, vy + vh - 6 - yy, bw - 1.5, 2);
          }
        });
        // track name scrolls across the top of the display
        ctx.save();
        ctx.beginPath(); ctx.rect(vx + 2, vy + 2, vw - 4, 12); ctx.clip();
        const label = `${TRACKS[st.track].name}   ·   ${st.playing ? 'PLAYING' : 'STOPPED'}   ·   `;
        ctx.font = FONT.small;
        const tw = ctx.measureText(label).width;
        const off = st.playing ? (st.t * 26) % tw : 0;
        for (let i = 0; i < 3; i++) {
          text(ctx, label, vx + 4 - off + i * tw, vy + 8, { baseline: 'middle', font: FONT.small, color: '#50d0a0' });
        }
        ctx.restore();

        // seek bar
        const sy = vy + vh + 6;
        bevelIn(ctx, r.x + 6, sy, r.w - 12, 12);
        const frac = st.pos / TRACKS[st.track].len;
        fill(ctx, r.x + 8, sy + 2, (r.w - 16) * frac, 8, C.titleA2);
        const kx = r.x + 6 + (r.w - 12) * frac;
        button(ctx, kx - 3, sy - 2, 7, 16, null);
        st.seekRect = { x: r.x + 6, y: sy - 2, w: r.w - 12, h: 16 };

        // transport
        const by = sy + 22;
        const btns = [['play', '▶'], ['pause', '❚❚'], ['stop', '■'], ['prev', '|◀'], ['next', '▶|']];
        st.btnRects = [];
        btns.forEach(([id, glyph], i) => {
          const bx = r.x + 6 + i * 30;
          button(ctx, bx, by, 28, 22, null, { pressed: id === 'play' && st.playing });
          ctx.save();
          ctx.fillStyle = '#000';
          ctx.font = '10px Tahoma, sans-serif';
          ctx.textAlign = 'center'; ctx.textBaseline = 'middle';
          ctx.fillText(glyph, bx + 14, by + 11);
          ctx.restore();
          st.btnRects.push({ x: bx, y: by, w: 28, h: 22, id });
        });
        // time
        const mm = Math.floor(st.pos / 60), ss = Math.floor(st.pos % 60);
        const tm = Math.floor(TRACKS[st.track].len / 60), ts = Math.floor(TRACKS[st.track].len % 60);
        bevelIn(ctx, r.x + r.w - 82, by, 76, 22);
        text(ctx, `${mm}:${String(ss).padStart(2, '0')} / ${tm}:${String(ts).padStart(2, '0')}`,
          r.x + r.w - 44, by + 11, { align: 'center', baseline: 'middle', font: FONT.small });
      },
      mouse(type, x, y, btn, win, papi) {
        if (type !== 'down') return;
        const b = win.maximized ? { x: 0, y: 0 } : { x: win.x, y: win.y };
        const ax = x + b.x + 3, ay = y + b.y + 40;
        for (const r of st.btnRects ?? []) {
          if (ax >= r.x && ax <= r.x + r.w && ay >= r.y && ay <= r.y + r.h) {
            papi.sound('click');
            if (r.id === 'play') { st.playing = true; papi.sound('music', { play: true, track: st.track }); }
            else if (r.id === 'pause') { st.playing = !st.playing; papi.sound('music', { play: st.playing, track: st.track }); }
            else if (r.id === 'stop') { st.playing = false; st.pos = 0; papi.sound('music', { play: false }); }
            else if (r.id === 'prev') { st.track = (st.track + TRACKS.length - 1) % TRACKS.length; st.pos = 0; if (st.playing) papi.sound('music', { play: true, track: st.track }); }
            else if (r.id === 'next') { st.track = (st.track + 1) % TRACKS.length; st.pos = 0; if (st.playing) papi.sound('music', { play: true, track: st.track }); }
            return;
          }
        }
        const sr = st.seekRect;
        if (sr && ax >= sr.x && ax <= sr.x + sr.w && ay >= sr.y && ay <= sr.y + sr.h) {
          st.pos = ((ax - sr.x) / sr.w) * TRACKS[st.track].len;
        }
      },
      dispose(win, papi) { papi.sound('music', { play: false }); },
    };
    return app;
  },
};

// ── MS-DOS Prompt ────────────────────────────────────────────
export const dos = {
  title: 'MS-DOS Prompt',
  icon: 'doc',
  w: 420, h: 268,
  single: true,

  create(arg, api) {
    const st = {
      lines: [
        'Microsoft(R) Windows 98',
        '   (C)Copyright Microsoft Corp 1981-1998.',
        '',
      ],
      input: '',
      cwd: 'C:\\WINDOWS',
      blink: 0,
      scroll: 0,
    };

    const FS = {
      'C:\\': ['WINDOWS <DIR>', 'PROGRAM~1 <DIR>', 'MYDOCU~1 <DIR>', 'AUTOEXEC.BAT', 'CONFIG.SYS', 'COMMAND.COM'],
      'C:\\WINDOWS': ['SYSTEM <DIR>', 'TEMP <DIR>', 'WIN.COM', 'NOTEPAD.EXE', 'WINMINE.EXE', 'SOL.EXE', 'CLOUD.BMP'],
      'C:\\MYDOCU~1': ['README.TXT', 'RESUME.TXT', 'TODO.TXT'],
    };

    function out(...ls) { st.lines.push(...ls); }

    function run(cmdline, papi) {
      const raw = cmdline.trim();
      const [cmd, ...args] = raw.split(/\s+/);
      const c = (cmd || '').toUpperCase();
      if (!c) return;
      switch (c) {
        case 'HELP':
          out('Available commands:', '',
            'CD       Changes the current directory.',
            'CLS      Clears the screen.',
            'DIR      Displays a list of files and subdirectories.',
            'ECHO     Displays messages.',
            'EXIT     Quits the MS-DOS Prompt.',
            'MEM      Displays the amount of used and free memory.',
            'TYPE     Displays the contents of a text file.',
            'VER      Displays the Windows version.',
            'WIN      Starts Windows.',
            '');
          break;
        case 'DIR': {
          const files = FS[st.cwd] ?? [];
          out(` Volume in drive C is MAIN`, ' Volume Serial Number is 1A2B-3C4D', ` Directory of ${st.cwd}`, '');
          for (const f of files) {
            const isDir = f.includes('<DIR>');
            const name = f.replace(' <DIR>', '');
            const [base, ext] = name.split('.');
            out(`${base.padEnd(8)} ${(ext ?? '').padEnd(3)} ${isDir ? '<DIR>' : String(1024 + base.length * 317).padStart(9)}  11-14-98  ${['9:41a', '2:07p', '11:23a'][base.length % 3]}`);
          }
          out('', `        ${files.length} file(s)      ${(files.length * 4096).toLocaleString()} bytes`,
            '                       2,147,483,648 bytes free', '');
          break;
        }
        case 'CD': {
          const target = (args[0] ?? '').toUpperCase();
          if (!target) { out(st.cwd, ''); break; }
          if (target === '..') { st.cwd = 'C:\\'; break; }
          if (target === '\\') { st.cwd = 'C:\\'; break; }
          const next = st.cwd === 'C:\\' ? `C:\\${target}` : `${st.cwd}\\${target}`;
          if (FS[next]) st.cwd = next;
          else out('Invalid directory', '');
          break;
        }
        case 'CLS': st.lines = []; break;
        case 'ECHO': out(args.join(' ') || 'ECHO is on.', ''); break;
        case 'VER': out('', 'Windows 98 [Version 4.10.1998]', ''); break;
        case 'MEM':
          out('', 'Memory Type        Total  =   Used  +   Free',
            '----------------  -------   -------   -------',
            'Conventional          640K       92K      548K',
            'Upper                 155K      155K        0K',
            'Extended (XMS)     130,432K   19,204K  111,228K',
            '----------------  -------   -------   -------',
            'Total memory       131,227K   19,451K  111,776K', '');
          break;
        case 'TYPE': {
          const f = (args[0] ?? '').toUpperCase();
          const key = { 'README.TXT': 'readme', 'RESUME.TXT': 'resume', 'TODO.TXT': 'todo' }[f];
          if (key) papi.open('notepad', key);
          else out(`File not found - ${f || ''}`, '');
          break;
        }
        case 'WIN': out('', 'Windows is already running.', ''); break;
        case 'EXIT': return 'exit';
        case 'DOOM': case 'DOOM.EXE':
          out('', 'Bad command or file name', '',
            "(You didn't install it. You never install it.)", '');
          break;
        case 'FORMAT':
          out('', 'WARNING: ALL DATA ON NON-REMOVABLE DISK', 'DRIVE C: WILL BE LOST!',
            'Proceed with Format (Y/N)? N', '', 'Good choice.', '');
          break;
        default:
          out(`Bad command or file name`, '');
      }
      return null;
    }

    const app = {
      title: 'MS-DOS Prompt', icon: 'doc', w: 424, h: 272, minW: 300, minH: 180,
      key(e, win, papi) {
        st.blink = 0;
        if (e.key === 'Enter') {
          out(`${st.cwd}>${st.input}`);
          const r = run(st.input, papi);
          st.input = '';
          if (r === 'exit') papi.close(win);
        } else if (e.key === 'Backspace') st.input = st.input.slice(0, -1);
        else if (e.key.length === 1) st.input += e.key;
        // trim scrollback
        if (st.lines.length > 400) st.lines = st.lines.slice(-400);
      },
      update(dt) { st.blink += dt; },
      draw(ctx, r, win) {
        fill(ctx, r.x, r.y, r.w, r.h, '#000000');
        ctx.font = '12px "Courier New", monospace';
        const LH = 13;
        const rows = Math.floor((r.h - 6) / LH);
        const all = [...st.lines, `${st.cwd}>${st.input}`];
        const start = Math.max(0, all.length - rows);
        for (let i = start; i < all.length; i++) {
          text(ctx, all[i], r.x + 4, r.y + 3 + (i - start) * LH, {
            font: '12px "Courier New", monospace', color: '#c8c8c8',
          });
        }
        if (Math.floor(st.blink * 2) % 2 === 0) {
          const lastY = r.y + 3 + (all.length - 1 - start) * LH;
          const w = ctx.measureText(`${st.cwd}>${st.input}`).width;
          fill(ctx, r.x + 4 + w, lastY, 7, 11, '#c8c8c8');
        }
      },
    };
    return app;
  },
};
